# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Geon Kim
title: Researcher for IoT-based System Engineering 
email: |
  kimgun472@gmail.com, 
  skygun88@kaist.ac.kr
website: skygun88.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  skygun88
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 건-김-a593bb24b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-3166-2432

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/geon.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Geon Kim and I am a graduate student majoring in Computer Science at KAIST.
  Currently, I am affiliated with the CDSN Lab at KAIST, and my research interests include building IoT-based distributed systems for smart services. 
  Specifically, I am studying preference learning in IoT-based smart spaces. 
  Preference learning involves using IoT sensors and actuators to gather data on user interactions, and then using RL to learn the user's preferred environment and how to control the system to reach that environment.
  Now, I am working on researching how to improve the level of personalization by incorporating IoT devices and user's personal information from visual data to learn user-state specific preferences, rather than single averaged preferences.
  In regards to this topic, I am working on my thesis which focuses on improving the control of robots to find the optimal observation position for personalized user-state sensing in real-world environments using Deep Reinforcement Learning (DRL).


content:
  ############################################# Education #############################################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Korea Advanced Institute of Science and Technology (KAIST)
        caption: 2017 - 2021
        sub_title: B.S. in Computer Science and Biology

      - layout: top
        title: Korea Advanced Institute of Science and Technology (KAIST)
        caption: 2021 - 2023
        sub_title: M.S. in Computer Science

  ############################################# Skills #############################################
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Programming Language
        description: |
          (Proficient) Python, C, SQL, MATLAB, (Experienced) C++, Scala, Kotlin, Java 

      - layout: top
        title: Frameworks/Tools
        description: |
          (Proficient) PyTorch, Django, Git, MySQL, MongoDB, (Experienced) ROS2, Docker, Unity, Keras, Tensorflow v2
      
      - layout: top
        title: Techniques
        description: |
          Reinforcement Learning, Deep Learning, RestAPI, MQTT

  ############################################# Projects #############################################
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EMG Onset Analysis
        sub_title: A project for benchmarking methods to estimate onset of muscular reaction from EMG signal 
        caption: MATLAB / EEGLAB toolbox
        # link: https://github.com/skygun88/IBS_EMG_onset_Analysis
        # link_text: Project Website
        additional_links:
          - title: Github repository  
            icon: fab fa-github
            url: https://github.com/skygun88/IBS_EMG_onset_Analysis
          - title: Summary Report
            icon: far fa-file-pdf
            url: https://github.com/skygun88/skygun88.github.io/blob/master/materials/ust_report.pdf
        description: | # this will include new lines to allow paragraphs
          The goal of this project is to develop a research assistant tool for a neuro-science laboratory that will automatically annotate the onset point of a rat's muscular reaction when stimulated. 
          The lab was previously burdened with manually annotating these points, so they need the assistant tool that can annotate at a human level of accuracy. 
          I focused on finding the best method for estimating the onset point of muscular reaction from EMG signals by comparing four different algorithms (Linear Envelope, TKEO, Sample Entropy, Integrated Profile) in terms of their Mean Squared Error (MSE) between the estimated point and ground truth, as well as their running time. 
          Additionally, I created a GUI-based interface to make it easy for researchers to use the estimation method.
          
      - layout: left
        title: ATeSS
        sub_title: A project for enhancing the test-road generation for autonomous driving 
        caption: Python, MATLAB / Simulink, Socket
        additional_links:
          - title: Github repository for original project
            icon: fab fa-github
            url: https://github.com/shhan1755/CS454-Final-Project
          - title: Workshop paper for revised version 
            icon: fas fa-link
            url: https://ieeexplore.ieee.org/document/9476236
          
        description: | # this will include new lines to allow paragraphs
          The original project was for an undergraduate lecture at KAIST. But, reivsed version was published in 2021 SBST.
          The goal of this project is to enhance existing search-based testing road generator for autonomous driving (AsFault).
          We improved AsFault by designing new crossover operators and proposing our new system test, Automatic Test Data Generator System for Self-Driving Car (ATeSS). 
          ATeSS can generate more challenging road maps than before.
          My works in this project are as follows. 1) overall system design and implementation, 2) implementation of road generation library for search-based algorithm, and 3) communication protocol design between road generator and Simulink-based autonomous driving simulator. 
          Road generation library is implemented by **Procedural Content Generation (PCG)**, and communication is based on **TCP/IP** socket protocols.

      - layout: left
        title: Emotion Joy
        sub_title: A project for designing the emotional interacting robot using vision and text processing.
        caption: Python, Arduino / OpenCV, Pytorch, PyQt5
        additional_links:
          - title: Github repository
            icon: fab fa-github
            url: https://github.com/skygun88/emotionSender_KROC
        description: | # this will include new lines to allow paragraphs
          The project aims to design an emotional interacting robot that assists in emotional interaction through text messages. 
          It analyzes the emotional expression in incoming text messages using the **fastText** library, categorizes them into emotions, and represents them using LED matrix face and arm displays. 
          Additionally, the robot detects the user's facial expressions through a connected webcam, recognizes their current emotion using a **CNN-based classifier**, and expresses the same emotion to show sympathy.
          My works in this project are as follows. 1) overall system design and implementation, 2) Simple text message application for demo using **PyQt5**. 
          3) Training of the CNN-based facial emotion classifier with opensource dataset using **PyTorch**, 4) **Arduino** programming execute robot movement and serial connection betwwen arduino and python script.

      
      - layout: left
        title: Hair Changer
        sub_title: A project for designing mobile hair change application using modern deepfake techniques
        caption: Python, Kotlin, Java / OpenCV, Tensorflow v2, Django, Sqlite3
        additional_links:
          - title: Github repositorys
            icon: fab fa-github
            url: https://github.com/jjm7307/HairChanger
          - title: Github repository
            icon: fab fa-github
            url: https://github.com/skygun88/HairChangerBackend
          - title: Summary Report
            icon: far fa-file-pdf
            url: https://github.com/skygun88/skygun88.github.io/blob/master/materials/hair_report1.pdf
          - title: Technical Report
            icon: far fa-file-pdf
            url: https://github.com/skygun88/skygun88.github.io/blob/master/materials/hair_report2.pdf
        description: | # this will include new lines to allow paragraphs
          This is a project for a undergraduate lecture in KAIST. The goal of this project is to design mobile hair change application using modern deepfake techniques. 
          The front end application provides users to take their face and desired hair style image to be changed. Then, our app send a hair change request to **Django**-based python backend server.  
          In the server, we used **FaceSwap** python library to exchange face of target hair image into user's requested face. Finally, result generated hair style changed images will be sent to users.
          My works in this project are as follows. 1) Django-based webserver implementation, 2) API for frontend-backend communication.

      # - layout: left
      #   title: CallForYou
      #   sub_title: A project for designing an interface for a convenient phone call application
      #   caption: Python, Kotlin / OpenCV, PyTorch, Django, Sqlite3
      #   additional_links:
      #     - title: Github repository
      #       icon: fab fa-github
      #       url: https://github.com/skygun88/CS584-Webserver
      #     - title: Summary Report
      #       icon: far fa-file-pdf
      #       url: https://github.com/skygun88/skygun88.github.io/blob/master/materials/callforyou_report.pdf
      #   description: | # this will include new lines to allow paragraphs
      #     This is a project for a graduate lecture in KAIST. The goal of this project is to design an interface for a convenient phone call application when user calls unfamiliar number.

      # - layout: left
      #   title: Minor projects
      #   sub_title: Minor projects at undergraduate student
      #   caption: Python, Kotlin / OpenCV, PyTorch, Django, Sqlite3
      #   additional_links:
      #     - title: Github repository
      #       icon: fab fa-github
      #       url: https://github.com/skygun88/CS584-Webserver
      #   description: | # this will include new lines to allow paragraphs
      #     These are projects when I was undergraudate student in KAIST. Some of them are projects for undergraduate lectures and others are projects for KAIST robotics club.


  ############################################# Experience #############################################
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CDSN Lab
        link: http://cds.kaist.ac.kr/
        sub_title: M.S. Program 
        caption: 2021 - 2023
        description: | # this will include new lines to allow paragraphs
            As a master's student, my focus of study was IoT-based smart services. 
            My main research was on a RL-based preference learning system in an IoT-enriched space; 
            a system that captures users' personalized preferences from their interactions with the space and provides them with a preferable environmental state. 
            Additionally, I utilized a mobile service robot as a tool to enhance the intelligence of the space for more accurate user preference capture. 
            In this regard, I have implemented a robot-incorporated distributed IoT system and have been designing a robot-IoT cooperative service for preference learning.

      - layout: left
        title: Microrobot Research
        link: https://mr.kaist.ac.kr/
        sub_title: KAIST Robotics Club
        caption: 2017 - 2021
        description: | # this will include new lines to allow paragraphs
            I was a member of the KAIST robotics club, Microrobot Research (MR) during my undergrad. 
            In the club, I gained skills and knowledge in for robot development like sensor & actuator technology, electronic circuit design, 2D & 3D modeling, and Arduino programming. 
            I worked on four projects including 1) a maze-escaping robot, 2) an emotion-expressing robot, 3) an emotional interaction robot, and 4) an AR interface development. 
            Details of each project are written in **Projects** section.

      - layout: left
        title: 2019 UST Research Internship  
        link: http://intern.ust.ac.kr
        sub_title: Internship Program on IBS
        caption: July, 2019 ~ August, 2019 
        description: | # this will include new lines to allow paragraphs
            During the summer of 2019, I participated in the UST Research Internship program. 
            I interned at the Institute for Basic Science(IBS)'s Center for Cognition and Sociality and learned about neuroscience research. 
            Specifically, I conducted biological experiments on rats and developed a research assistance program for the laboratory (**EMG onset analysis** in project sections).

      
  
  ############################################# Publications #############################################
  - title: Publications
    layout: list
    content: # this will include new lines to allow paragraphs
      - layout: top
        title: International Conferences
        description: |
          - S. Han, J. Kim, G. Kim, J. Cho, J. Kim, and S. Yoo, “Preliminary evaluation of path-aware crossover operators for search-based test data generation for autonomous driving”, in 2021 IEEE/ACM 14th International Workshop on Search-Based Software Testing (SBST), 2021.
          - G. Kim et al., “Towards deployment of mobile robot driven preference learning for user-state-specific thermal control in a real-world smart space,” in Proceedings of the 38th ACM/SIGAPP Symposium on Applied Computing, 2023, pp. 724–731.
          - G, Kim et al., "Exploring Technical Challenges for Thermal Sensation Estimation in Mobile Robot driven Personalized Thermal Control", in 20th International Conference on Ubiquitous Robots (UR 2023), 2023 (Accepted)
      - layout: top
        title: Domestic Conferences
        description: |
          - G. Kim, H. Kim, D. Lee, and Y. Kim, “Dqn based indoor thermal control for activity-specific user preference”, in 2022 한국컴퓨터종합학술대회 (KCC2022), 2022. 
          - G. Kim, H. Kim, and D. Lee, “A deep reinforcement learning based approach for user preference learning in a smart space”, in 2021 한국컴퓨터종합학술대회 (KCC2021), 2021

  ############################################# Awards #############################################
  - title: Scholarships and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      -  KCC2021 학부생/주니어논문경진대회, 사물인터넷 부문, 우수상, 2021



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
