# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Geon Kim
title: IoT-based Smart System Researcher
email: kimgun472@gmail.com
website: skygun88.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  skygun88
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 건-김-a593bb24b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Geon

content:
  ############################################# Education #############################################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Korea Advanced Institute of Science and Technology (KAIST)
        caption: 2017 - 2021
        sub_title: B.S. in Computer Science and Biology

      - layout: top
        title: Korea Advanced Institute of Science and Technology (KAIST)
        caption: 2021 - Present (scheduled in August 2023)
        sub_title: M.S. in Computer Science

  ############################################# Skills #############################################
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Programming Language
        description: |
          (Proficient) Python, C, SQL, MATLAB, (Experienced) C++, Scala, Kotlin, Java 

      - layout: top
        title: Frameworks/Tools
        description: |
          (Proficient) PyTorch, Django, ROS2, Git, MongoDB, (Experienced) Docker, Unity, Keras, Tensorflow v2
      
      - layout: top
        title: Techniques
        description: |
          Reinforcement Learning, Deep Learning, RestAPI, MQTT

  ############################################# Projects #############################################
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  ############################################# Experience #############################################
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CDSN Lab
        link: http://cds.kaist.ac.kr/
        # link_text: boringcompany.com
        sub_title: M.S. Program 
        caption: September 2021 - Present
        description: | # this will include new lines to allow paragraphs
            As a master student, I studyed IoT-based smart service. The main research point was RL-based preference learning system in IoT-enriched space; system that captures user's personalized preference from interaction between user and space, and provides user preferable environmental state.
            In addtion, I adopted the mobile service robot as a tool to increase the space intelligence for capturing more accurate user preference.

      - layout: left
        title: Microrobot Research
        link: https://mr.kaist.ac.kr/
        # link_text: boringcompany.com
        sub_title: KAIST Robotics Club
        caption: 2017 - 2021
        quote: >
         This is KAIST robotics club for undergraduate students. 
        description: | # this will include new lines to allow paragraphs
            I spent 4 years on MR and participated 4 projects. 
  
  ############################################# Publications #############################################
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - G. Kim, H. Kim, D. Lee, and Y. Kim, “Dqn based indoor thermal control for activity-specific user preference”, in 2022 한국컴퓨터종합학술대회 (KCC2022), 2022. 
      - S. Han, J. Kim, G. Kim, J. Cho, J. Kim, and S. Yoo, “Preliminary evaluation of path-aware crossover operators for search-based test data generation for autonomous driving”, in 2021 IEEE/ACM 14th International Workshop on Search-Based Software Testing (SBST), 2021.
      - G. Kim, H. Kim, and D. Lee, “A deep reinforcement learning based approach for user preference learning in a smart space”, in 2021 한국컴퓨터종합학술대회 (KCC2021), 2021

  - title: Scholarships and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      -  KCC2021 학부생/주니어논문경진대회, 사물인터넷 부문, 우수상, 2021

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
